### ISSUE TITLE
Milestone Tracker

### ISSUE THREAD

**Issue by necoline** [developmentseed/SERVIR-Amazonia#2]
### Milestone 1.1: Design Review and Usability Testing Report
- [x] [RAMI usability report](https://docs.google.com/document/d/1IwgTnDId5IVTuW1ZWXF8oDu0qq6wj6o9X06JKWlI9rA/edit?ts=60ae71aa)
- [x] AMZ usability report
  -[interface overview video](https://drive.google.com/file/d/1ILVJtxpHLfTu-7ujSM-DRsz-3rG0FV0c/view)
  - [usability report](https://docs.google.com/document/d/1X2mjJarea0WIKLl5f_sqX582NMvoRNKh1bGflBg5vf0/edit)
  - user feedback
- [x] CoMiMo usability report
  - [report](https://docs.google.com/document/d/1zpN22sIW4wNicRWuw0wfoB1ithjNrU-NuXKwwq6_cPo/edit)
  -[ heuristic evaluation](https://docs.google.com/spreadsheets/d/1IjU9yppxC_EsY1B_4F3SHW5QJNC6PJ8u/edit#gid=1395480243)

### Milestone 1.2: Design Template
- [x] RAMI design guidance
   - [Branding](https://www.figma.com/file/0e9Zb6FHxmuSisuzayAnuK/RAMI-Brand?node-id=16%3A61)
   - Data layer design & guidelines
- [ ] AMZ design guidance
   - UI wireframes
- [ ] common design assets
   - SERVIR design system
     - [presentation](https://www.figma.com/file/yyISCHySPehFHd4rUNWyj5/SERVIR--Amazonia-_-Design-System?node-id=94%3A2556)
     - [design system](https://www.figma.com/file/yyISCHySPehFHd4rUNWyj5/SERVIR--Amazonia-_-Design-System?node-id=0%3A1)
   - guidance on component development
   - data layers
   - downloaded data redesign

## Front-end and back-end design templates for GEE-based and non-GEE based applications.
- [ ] Milestone 2.1: Architectural Design Review

## Design implementation and capacity building.
- [ ] Milestone 3.1: Sprint Plans, Architectural Design Documents
- [ ] Milestone 3.2: Capacity Building Support Logs: Report of how budgeted hours were spent with notes on what was accomplished

## UX/UI training and co-development sessions with SERVIR-Amazonia UX/UI consultant and GIT team.
- [ ] Milestone 4.1: Completion of Workshops
- [ ] Milestone 4.2: Cloud Resource Consultation Logs: Report of how budgeted hours were spent with notes on what was accomplished
- [ ] Milestone 4.3: Project Plan Template

## Documentation listing recommendations and guidance on UX/UI expertise needed at hub given current capabilities of technical team involved in app development.
- [ ] Milestone 5.1: Application Testing and Monitoring System Documentation
- [ ] Milestone 5.2: Testing and Monitoring Training
